### ISSUE TITLE
how to implement a profile of  energy consumption monitoring of nodes on fit iot lab 

### ISSUE THREAD

**Issue by yahya-93** [iot-lab/iot-lab-training#3]
Hi everyone
I want to test the AES message encryption mechanism on M3 and ST-Lorawamn nodes and collect information about the energy consumption of the nodes during the encryption phase and the computing time
the problem I found is that the experiment on fit iot lab can't be launched using a power consumption monitoring profile without the tutorial-M3.elf firmware
im  getting the following message error
rbah@grenoble:~/iot-lab/parts/contiki/examples/ipv6/rpl-udp$ plot_oml_consum -p -i  ~/.iot-lab/255409/consumption/m3_103.oml
/usr/local/lib/python3.7/dist-packages/oml_plot_tools/common.py:144: ConversionWarning: Some errors were detected !
    Line #2128 (got 5 columns instead of 8)
  invalid_raise=False)
Traceback (most recent call last):
  File "/usr/local/bin/plot_oml_consum", line 24, in <module>
    oml_plot_tools.consum.main()
  File "/usr/local/lib/python3.7/dist-packages/oml_plot_tools/consum.py", line 157, in main
    consumption_plot(data, opts.title, selection)
  File "/usr/local/lib/python3.7/dist-packages/oml_plot_tools/consum.py", line 117, in consumption_plot
    oml_plot(data, title, [MEASURES_D[value]])
  File "/usr/local/lib/python3.7/dist-packages/oml_plot_tools/consum.py", line 139, in oml_plot
    plt.figure()
  File "/usr/local/lib/python3.7/dist-packages/matplotlib/pyplot.py", line 533, in figure
    **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/matplotlib/backend_bases.py", line 161, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/usr/local/lib/python3.7/dist-packages/matplotlib/backends/_backend_tk.py", line 1046, in new_figure_manager_given_figure
    window = Tk.Tk(className="matplotlib")
  File "/usr/lib/python3.7/tkinter/__init__.py", line 2023, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
rbah@grenoble:~/iot-lab/parts/contiki/examples/ipv6/rpl-udp$ 
SVP CAN U HELP ME

**Comment by fsaintma** [comment]
Hi @yahya-93 
I'm sorry but it's impossible. Indeed the ST-Lorawan nodes don't provide this feature.
We will soon deploy a fix to check that profile monitoring is allowed on the nodes (i.e. monitoring hardware is available on the IoT-LAB gateway) and in this case returned an error when updating or associating profiles during experiments submission.
Sorry for the inconvenience.

**Comment by yahya-93** [comment]
Hello @fsaintma , thank you for your reply.
I have a question please 
I want to use a M3 node to monitor the power consumption. while in the existing tutorial on the platform website associates the power consumption profile to the  firmware tutorial_m3.elf which is created in advance to turn on/off the device LEDs periodically
How can we use other firmware (if they exist. where can i get them) to update and associate profiles during experiments submission which allow to use the sensors of node M3 to collect information like temperature then launch the energy consumption profile
